# This workflow allows teh creation of a Codespace on the actual repo

name: Create_Codespace

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allow to be called from a differnt workflow
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  createCodespace:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Create Codespace
        run: gh cs create -b main -m "standardLinux32gb"




